WebForFunThailand/noobtoberfest

- .gitignore
- shoot-me-if-you-can/index.html
- shoot-me-if-you-can/info.json
Add new game: Shoot me if you can
> Shoot me if you can

- README.md
> [FIX] typo in Thai language

- pull_request_template.md
grammatical correction for the pr form
Your Email Address: mail@chayapatr.com
> grammatical correction

- .gitignore
- quick-thai-name/index.html
- quick-thai-name/info.json
- fix .gitignore can not add index.html
- Add Quick Thai Name Game 
> add quick thai name game / fix .gitignore can not add index.html

- pressffornoreason/info.json
- pressffornoreason/script.js
- pressffornoreason/style.css
add a game called press f for no reason (that's it)
Your Email Address: mail@chayapatr.com
> add game: pressffornoreason

- build.js
- template.html
What I do:
- change the game link's target to a new tab. make the web better.
- link can hover and color will change! greater visualization 918 ea
> Update UI and UX

- .gitignore
- pressffornoreason/index.html
remove index.html from .gitignore
- [x ] Yes (If you select yes, please type your email below)
Your Email Address: mail@chayapatr.com
> [pressffornoreason] add index.html / remove index.html from .gitignore

- trob./index.html
- trob./info.json
> Prismacolor patch 1

- 10-sec-clicker/index.html
- 10-sec-clicker/info.json
- [/ ] Yes (If you select yes, please type your email below)
Your Email Address: safe.suk@gmail.com
> feat: add 10-sec-clicker game~

- pressffornoreason/index.html
change interval time from 10 to 50 (time in a game is slower than irl for some reason, idk)
Your Email Address: mail@chayapatr.com
> [pressffornoreason] [wip] change interval time

- TheDIIIIIV/index.html
- TheDIIIIIV/info.json
'The DIIIIIIV' game
Click 'Close' until you can click 'GO TO NEXT LEVEL'
Yes 
Your Email Address: (max.jakkapat@gmail.com)
> create the DIIIIIV

- Aleph Zero/index.html
- Aleph Zero/info.json
Add game "Aleph Zero"
Yes, I want an early bird ticket for Hacktoberfest BKK.
Email Address: aomkirby123@gmail.com
> :fire: Aleph Zero

- spot-the-difference/index.html
- spot-the-difference/info.json
Create 'Spot The Difference' game: the game to find the different characters in 60 seconds
Your Email Address: p.siriphanthong@gmail.com
> Create 'Spot The Difference' game

- 5-rps/index.html
- 5-rps/info.json
Add 5 rock paper scissors variant game (called "Rock-Paper-Scissors-Spock-Lizard") It is from ["Big Bang theory"](https://bigbangtheory.fandom.com/wiki/Rock,_Paper,_Scissors,_Lizard,_Spock). 
Your Email Address: yuttakhanbaingen@gmail.com
> Add 5-rock paper scissors game

- good-night-dear/index.html
- good-night-dear/info.json
You are a คุณแม่วัยใส and recently bought a new bedtime story book for your kids. However, the book is entirely written in สก๊อย language. You have to translate them into Thai before reading for your kids or else they will grow up into สก๊อย.
Your Email Address: moo_suthep@hotmail.com
> + New game: Good night, dear.

- spot-the-difference/index.html
- update user interface for responsive
- add more pair characters
Your Email Address: p.siriphanthong@gmail.com
> Update 'Spot The Difference' game

- roulette/index.html
- roulette/info.json
Add a new game "BallSpin Roulette". just play by click on "spin" button.
Your Email Address: supawit.ruen@mail.kmutt.ac.th
> Add roulette game!

- math-master/index.html
- math-master/info.json
Your Email Address: (Optional) Jabont@hotmail.com
> add Math master game

- turn-dark/index.html
- turn-dark/info.json
Add a new game "Turn dark".
Yes,
Your Email Address: kijpokin.nga@hotmail.com
> [Turn-dark] Add turn-dark game

- turn-dark/index.html
bugfix some cases light not toggle
Yes
Your Email Address: Kijpokin.nga@hotmail.com
> [Turn-dark] Fix bug light not off in first index

- good-night-dear/index.html
- good-night-dear/info.json
This PR are fixes to my game (#25)
\+ Add colors for chrome, windows phone, and iOS
\+ Add fable source
~ Fix modal border color from gray to black
~ Change to Vue.js for production
~ Fix info typo (Skoy should be capitalization because it's a language, bruh)
Your Email Address: moo_suthep@hotmail.com
> [Good night, dear.] Add color meta(s), fable source, and fixes

- android-war/index.html
- android-war/info.json
- avenger-puzzle/index.html
- avenger-puzzle/info.json
Your Email Address: (Optional) Jabont@hotmail.com
> Add 2nd Game - Android War!

- avenger-puzzle/index.html
Change how to random before start game
> change random algorithm⚜️

- android-war/index.html
> Add facebook meta

- type-in-1-sec/index.html
- type-in-1-sec/info.json
> add type in 1 sec game

- type-in-1-sec/index.html
This PR is for fixing due to I hurry to finish my game.
> fix: type in 1 sec game for checking key

- README.md
Just fix the wrong numbered list in Rules section in Readme.md. So i add non-breaking spaces to prevent markdown to auto list the number.
> Fix the wrong numbered list in Rules section in Readme.md

- dream-time/index.html
- dream-time/info.json
- trob/index.html
- trob/info.json
> Add new game: dream-time.

- README.md
> grammar fix on README

- 10-sec-clicker/index.html
Implemented click button for fixing bug that can click everywhere
> fix(10-sec-clicker): implemented click button for fixing bug that can click everywhere

- BNK48-Guess-the-name/index.html
comment unnecessary code
- css file link
- container height to see whole detail
> fix no css file, container height to equal area height

- fruit-vegetable/index.html
- fruit-vegetable/info.json
Implement new game 'fruit-vegetable', implemented with Phaser 3.
The code is still pretty messy but should work properly.
Your Email Address: tanapol.raa@gmail.com
> add fruit-vegetable game

- 10-sec-clicker/index.html
- roulette/index.html
Your Email Address: patcharapol.pal@gmail.com
> enhance 10-sec-clicker

- 10-sec-clicker/index.html
- roulette/index.html
> enhance Roulette to be able to move any position

- predict-number/index.html
- predict-number/info.json
> add predict number grame

- beat-me-if-you-can/index.html
- beat-me-if-you-can/info.json
> Add beat me if you can game

- 10-sec-clicker/info.json
- 5-rps/info.json
- Aleph Zero/info.json
- BNK48-Guess-the-name/info.json
- Breakout!/info.json
- TheDIIIIIV/info.json
- android-war/info.json
- avenger-puzzle/info.json
- beat-me-if-you-can/info.json
- build.js
- config.js
- dream-time/info.json
- fruit-vegetable/info.json
- good-night-dear/info.json
- math-master/info.json
- predict-number/info.json
- pressffornoreason/info.json
- quick-thai-name/info.json
- roulette/info.json
- shoot-me-if-you-can/info.json
- spot-the-difference/info.json
- template.html
- trob./info.json
- trob/info.json
- turn-dark/info.json
- type-in-1-sec/info.json
> Update for noobtoberfest 2020

- build.js
- config.js
- template.html
> Update design 

- build.js
- template.html
...please describe what you do in this pull request...
> fix: change banner font size and topic container width

- bogotetris/index.html
- bogotetris/info.json
Add Bogotetris, a Tetris Game developed in pure JavaScript
> Add Bogotetris

- arrow-director/index.html
- arrow-director/info.json
Create Arrow-Direction game from pure html, javascript
> Add Game: Arrow-Direction

- README.md
I add the translation for consistency because there is no translation for contribution guide yet.
> Add translation for contribution guide.

- nud-yim/index.html
- nud-yim/info.json
> add game nud-yim

- which-color/index.html
- which-color/info.json
Create Which Color game from pure html, javascript
> Add game: Which Color !?

- boss-battle/index.html
- boss-battle/info.json
A simple replication of turn-based battle system. 
Edit 1: Done the basic game system.
> Add game Boss Battle

- REMEMBER ME/index.html
- REMEMBER ME/info.json
> 💕 Add REMEMBER ME 💕

- color-matcher/index.html
- color-matcher/info.json
...please describe what you do in this pull request...
> add color-matcher

- guess-the-number/index.html
- guess-the-number/info.json
Guess the number is a game that lets you guess the random number within the limited number of times. There is no time limit and any other rules. This game is written purely using vanilla JavaScript because I want to try writing something without library once in a while.
Please enjoy!
----
> Guess the number
